-- AUTO-GENERATED by app/scripts/build_seed.mjs — Supabase SQL Editor에서 Run (service key 불요)
-- 정답(answer) 포함: 서버측 mission/course_mission 테이블. anon은 mission_public 뷰로만 조회(answer 숨김).
-- 멱등: 재실행 시 on conflict do update.
begin;

insert into place (place_id,name,theme_tags,route_category,stay_minutes,hub_minutes,transfer_count,route_type,verified,indoor,photo_friendly,photo_url,photo_source,photo_license,photo_attribution,needs_field_shoot,lat,lng) values
('B11','연동교회',ARRAY['faith']::theme_tag[],'required',30,2,0,'walk',true,true,true,null,null,null,null,true,37.57366,127.0015),
('D5','광장시장',ARRAY['neighbor','fun']::theme_tag[],'required',60,8,0,'walk',true,true,true,null,null,null,null,true,37.57006,126.99895),
('C3','전태일기념관+다리',ARRAY['history']::theme_tag[],'required',50,18,0,'walk',false,true,true,null,null,null,null,true,37.56842,126.98938),
('A7','정동제일교회',ARRAY['faith']::theme_tag[],'select',20,24,0,'noTransfer',false,false,true,null,null,null,null,true,37.56541,126.97273),
('B1','배재학당역사박물관',ARRAY['faith']::theme_tag[],'select',40,24,0,'noTransfer',false,true,true,null,null,null,null,true,37.56401,126.9726),
('B2','이화박물관(심슨기념관)',ARRAY['faith']::theme_tag[],'select',30,24,0,'noTransfer',false,true,true,null,null,null,null,true,37.56608,126.97145),
('B6','승동교회',ARRAY['faith']::theme_tag[],'select',20,16,0,'walk',false,true,true,null,null,null,null,true,37.57158,126.98607),
('A15','양화진선교사묘원',ARRAY['faith']::theme_tag[],'select',60,51,2,'2transfer',false,false,true,null,null,null,null,true,37.54654,126.91093),
('A3','서대문형무소역사관',ARRAY['history']::theme_tag[],'select',90,31,1,'1transfer',false,true,true,null,null,null,null,true,37.57461,126.95561),
('A4','중명전',ARRAY['history']::theme_tag[],'select',40,26,0,'noTransfer',false,true,true,null,null,null,null,true,37.56673,126.97252),
('A2','대한민국역사박물관',ARRAY['history']::theme_tag[],'select',90,24,1,'1transfer',false,true,true,null,null,null,null,true,37.57399,126.97786),
('A10','광화문광장',ARRAY['history']::theme_tag[],'select',30,24,1,'1transfer',false,false,true,null,null,null,null,true,37.5726,126.97692),
('A1','평화의 소녀상',ARRAY['history']::theme_tag[],'select',15,24,1,'1transfer',false,false,true,null,null,null,null,true,37.57497,126.98046),
('C2','이회영기념관',ARRAY['history']::theme_tag[],'select',40,34,1,'1transfer',false,true,true,null,null,null,null,true,37.57296,126.96564),
('A5','청계천(청계광장)',ARRAY['ecology']::theme_tag[],'select',40,8,0,'walk',false,false,true,'https://www.kogl.or.kr/recommend/recommendView.do?recommendIdx=3120','한국관광공사(공공누리 포털)','공공누리 제1유형','본 저작물은 한국관광공사에서 공공누리 제1유형으로 개방한 ''청계광장''을 이용하였으며, 공공누리(www.kogl.or.kr)에서 무료로 다운로드할 수 있습니다.',false,37.56907,126.97759),
('A6','서울로 7017',ARRAY['ecology']::theme_tag[],'select',40,26,0,'noTransfer',false,false,true,null,null,null,null,true,37.55674,126.9706),
('A9','영천시장',ARRAY['neighbor']::theme_tag[],'select',40,31,1,'1transfer',false,true,true,null,null,null,null,true,37.57048,126.96114),
('D3','세운옥상',ARRAY['fun']::theme_tag[],'select',20,12,0,'walk',false,false,true,null,null,null,null,true,37.56914,126.99524),
('D4','익선동 한옥거리',ARRAY['fun']::theme_tag[],'select',40,15,0,'walk',false,false,true,null,null,null,null,true,37.57344,126.98978),
('A8','교보문고 광화문점',ARRAY['fun']::theme_tag[],'select',40,24,1,'1transfer',false,true,true,null,null,null,null,true,37.5708,126.97791)
on conflict (place_id) do update set name=excluded.name,theme_tags=excluded.theme_tags,route_category=excluded.route_category,stay_minutes=excluded.stay_minutes,hub_minutes=excluded.hub_minutes,transfer_count=excluded.transfer_count,route_type=excluded.route_type,verified=excluded.verified,indoor=excluded.indoor,photo_friendly=excluded.photo_friendly,photo_url=excluded.photo_url,photo_source=excluded.photo_source,photo_license=excluded.photo_license,photo_attribution=excluded.photo_attribution,needs_field_shoot=excluded.needs_field_shoot,lat=excluded.lat,lng=excluded.lng;

insert into course (course_id,type,place_ids) values
('common','common',ARRAY['B11','D5','C3']),
('rc_jeongdong','recommended',ARRAY['A7','B1','B2','A4']),
('rc_gwanghwamun','recommended',ARRAY['A2','A10','A8','A1']),
('rc_insadong','recommended',ARRAY['B6','D3','D4']),
('rc_seodaemun','recommended',ARRAY['A3','A9','C2']),
('rc_eco','recommended',ARRAY['A5','A6','A15'])
on conflict (course_id) do update set type=excluded.type,place_ids=excluded.place_ids;

insert into mission (mission_id,place_id,type,evidence_types,requires_reservation,outdoor,fallback_mission,answer) values
('m_B11_1','B11','observe_quiz',ARRAY['group_photo']::evidence_type[],false,false,null,'1894년 시작(무어·이길함·서상륜), 게일 1900년 초대 담임목사 부임'),
('m_B11_2','B11','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_B11_3','B11','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_D5_1','D5','interview_experience',ARRAY['purchase','photo']::evidence_type[],false,false,'분식 메뉴판·가게 간판을 사진으로 담아 무엇을 골랐는지 기록',null),
('m_D5_2','D5','interview_experience',ARRAY['voice','photo']::evidence_type[],false,false,'가게 연혁·메뉴판을 찾아 사진+메모',null),
('m_D5_3','D5','photo_reenact',ARRAY['group_photo']::evidence_type[],false,false,null,null),
('m_C3_1','C3','observe_quiz',ARRAY['photo']::evidence_type[],false,false,null,null),
('m_C3_2','C3','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_C3_3','C3','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_A7_1','A7','observe_quiz',ARRAY['group_photo']::evidence_type[],false,true,null,'정동제일교회 / 아펜젤러'),
('m_A7_2','A7','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_A7_3','A7','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_B1_1','B1','observe_quiz',ARRAY['memo']::evidence_type[],false,false,null,'현장 전시 확정(교훈/첫 졸업생 등)'),
('m_B1_2','B1','photo_reenact',ARRAY['group_photo']::evidence_type[],false,false,null,null),
('m_B1_3','B1','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_B2_1','B2','observe_quiz',ARRAY['memo']::evidence_type[],false,false,null,'현장 전시 확정(첫 학생·설립자)'),
('m_B2_2','B2','photo_reenact',ARRAY['group_photo']::evidence_type[],false,false,null,null),
('m_B2_3','B2','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_B6_1','B6','observe_quiz',ARRAY['memo']::evidence_type[],false,false,null,'백정 박성춘을 받아들인 이야기'),
('m_B6_2','B6','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_A15_1','A15','reflect_share',ARRAY['photo','memo']::evidence_type[],true,true,null,null),
('m_A15_2','A15','observe_quiz',ARRAY['photo']::evidence_type[],false,true,null,'현장 확정(선교사 1인의 이름·한 일)'),
('m_A3_1','A3','observe_quiz',ARRAY['photo']::evidence_type[],false,false,null,'현장 명패 확정'),
('m_A3_2','A3','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_A3_3','A3','reflect_share',ARRAY['voice','memo']::evidence_type[],false,false,null,null),
('m_A4_1','A4','observe_quiz',ARRAY['memo']::evidence_type[],false,false,null,'현장 확정(원래 이름·을사늑약 관련)'),
('m_A4_2','A4','interview_experience',ARRAY['photo']::evidence_type[],false,false,'옥새 전시물 사진+설명',null),
('m_A4_3','A4','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_A2_1','A2','photo_reenact',ARRAY['group_photo']::evidence_type[],false,false,null,null),
('m_A2_2','A2','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_A2_3','A2','observe_quiz',ARRAY['photo']::evidence_type[],false,false,null,null),
('m_A10_1','A10','observe_quiz',ARRAY['memo']::evidence_type[],false,true,null,null),
('m_A10_2','A10','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_A10_3','A10','reflect_share',ARRAY['voice','memo']::evidence_type[],false,true,null,null),
('m_A1_1','A1','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_A1_2','A1','observe_quiz',ARRAY['photo']::evidence_type[],false,true,null,null),
('m_A1_3','A1','reflect_share',ARRAY['voice','memo']::evidence_type[],false,true,null,null),
('m_C2_1','C2','observe_quiz',ARRAY['memo']::evidence_type[],false,false,null,'신흥무관학교'),
('m_C2_2','C2','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_A5_1','A5','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_A5_2','A5','reflect_share',ARRAY['memo']::evidence_type[],false,true,null,null),
('m_A6_1','A6','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_A6_2','A6','observe_quiz',ARRAY['photo']::evidence_type[],false,true,null,null),
('m_A9_1','A9','interview_experience',ARRAY['purchase','photo']::evidence_type[],false,false,'대표 먹거리집 간판·메뉴를 사진으로 담기',null),
('m_A9_2','A9','interview_experience',ARRAY['voice','photo']::evidence_type[],false,false,'가게 간판·연혁 표시를 찾아 사진+메모',null),
('m_A9_3','A9','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_D3_1','D3','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_D4_1','D4','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_D4_2','D4','observe_quiz',ARRAY['photo']::evidence_type[],false,true,null,null),
('m_A8_1','A8','observe_quiz',ARRAY['memo']::evidence_type[],false,false,null,'현장 도서·서가 확정'),
('m_A8_2','A8','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_A8_3','A8','observe_quiz',ARRAY['photo']::evidence_type[],false,true,null,null)
on conflict (mission_id) do update set place_id=excluded.place_id,type=excluded.type,evidence_types=excluded.evidence_types,requires_reservation=excluded.requires_reservation,outdoor=excluded.outdoor,fallback_mission=excluded.fallback_mission,answer=excluded.answer;

insert into course_mission (mission_id,scope,type,evidence_types,requires_reservation,outdoor,fallback_mission,answer) values
('m_ALL_1','course','reflect_share',ARRAY['memo']::evidence_type[],false,false,null,null),
('m_ALL_2','course','photo_reenact',ARRAY['group_photo']::evidence_type[],false,true,null,null),
('m_ALL_3','course','interview_experience',ARRAY['photo']::evidence_type[],false,true,'발자국 따라 걷는 장면을 조원끼리 연출해 촬영(외부인 접촉 불필요)',null)
on conflict (mission_id) do update set type=excluded.type,evidence_types=excluded.evidence_types,requires_reservation=excluded.requires_reservation,outdoor=excluded.outdoor,fallback_mission=excluded.fallback_mission,answer=excluded.answer;

insert into reading (reading_id,served_place_ids,theme,word_target,operational_note,source_ref) values
('R-A1',ARRAY['A1'],'neighbor',800,'야외. 도로 인접 — 동선 통제 주의. 수요시위 등 현장 상황 변동 가능.','아시아경제 https://www.asiae.co.kr/article/2017100410092815830 ; 뉴시스(공공조형물 제1호) https://www.newsis.com/view/NISX20170928_0000108502'),
('R-A10',ARRAY['A10'],'neighbor',800,'야외. 여름 분수 가동, 그늘 적음 — 무더위 시 인접 실내(역사박물관·교보문고) 대피.','뉴시스(2022 재개장) https://www.newsis.com/view/NISX20220805_0001969537 ; 나무위키 광화문광장 https://namu.wiki/w/광화문광장'),
('R-A15',ARRAY['A15'],'faith',800,'월~토 10:00–17:00, 일요일 휴무. 해설 사전예약(02-332-9174). 합정역 7번 출구 도보 약 10분.','양화진외국인선교사묘원 공식 https://yanghwajin.net/ ; 위키백과 https://ko.wikipedia.org/wiki/양화진외국인선교사묘원'),
('R-A2',ARRAY['A2'],'history',800,'null','문체부 보도자료(개관) https://mcst.go.kr/kor/s_notice/press/pressView.jsp?pSeq=12481 ; 위키백과 https://ko.wikipedia.org/wiki/대한민국역사박물관'),
('R-A3',ARRAY['A3'],'history',800,'null','한국민족문화대백과 서대문형무소 https://encykorea.aks.ac.kr/Article/E0066513 ; 우리역사넷 https://contents.history.go.kr/mobile/kc/view.do?levelId=kc_r400150'),
('R-A4',ARRAY['A4'],'history',800,'null','위키백과 중명전 https://ko.wikipedia.org/wiki/중명전 ; 국가유산청 중명전 https://royal.khs.go.kr/ROYAL/contents/R104020000.do?groupCode=dsg&programCode=exhibition2'),
('R-A5',ARRAY['A5'],'ecology',800,'야외 도보 동선(청계천변, 광장시장~광화문). 여름 물놀이 구간 안전 유의.','한국민족문화대백과 청계천 https://encykorea.aks.ac.kr/Article/E0068490 ; 한국일보 https://www.hankookilbo.com/News/Read/201203291797847459'),
('R-A6',ARRAY['A6'],'ecology',800,'야외, 그늘 거의 없음 — 해질녘 배치 권장, 얼음물·모자 필수.','위키백과 서울로 7017 https://ko.wikipedia.org/wiki/서울로_7017 ; 서울사랑 https://love.seoul.go.kr/articles/4254'),
('R-A7',ARRAY['A7'],'faith',800,'null','한국민족문화대백과 정동제일교회 https://encykorea.aks.ac.kr/Article/E0050108 ; 위키백과 정동제일교회 https://ko.wikipedia.org/wiki/정동제일교회'),
('R-A8',ARRAY['A8'],'faith',800,'실내·냉방(폭염 대피 거점). 09:30–22:00, 설·추석 당일 휴점. 광화문역 지하 직결.','교보문고 광화문점 매장안내 https://store.kyobobook.co.kr/store-info/001'),
('R-A9',ARRAY['A9'],'neighbor',800,'null','서대문구청 영천시장 https://www.sdm.go.kr/culture/attraction/sub2080.do ; 지역N문화 https://ncms.nculture.org/market/story/9651'),
('R-B1',ARRAY['B1'],'faith',800,'null','한국민족문화대백과 배재학당 https://encykorea.aks.ac.kr/Article/E0021918 ; 국사편찬위 우리역사넷 https://contents.history.go.kr/mobile/kc/view.do?levelId=kc_o401410'),
('R-B11',ARRAY['B11'],'faith',800,'null','한국민족문화대백과 연동교회 https://encykorea.aks.ac.kr/Article/E0036749 ; 연동교회 공식 https://www.ydpc.org/Page/Index/117532'),
('R-B2',ARRAY['B2'],'faith',800,'null','위키백과 심슨기념관 https://ko.wikipedia.org/wiki/서울_이화여자고등학교_심슨기념관 ; OpenHouse Seoul https://www.ohseoul.org/post/이화학당-이화여자고등학교-심슨기념관/page/134'),
('R-B6',ARRAY['B6'],'faith',800,'null','위키백과 승동교회 https://ko.wikipedia.org/wiki/승동교회 ; 한국민족문화대백과 박성춘 https://encykorea.aks.ac.kr/Article/E0076573'),
('R-C2',ARRAY['C2'],'history',800,'null','위키백과 이회영 https://ko.wikipedia.org/wiki/이회영 ; 경향신문 https://www.khan.co.kr/article/201808122053025'),
('R-C3',ARRAY['C3'],'history',800,'null','한국민족문화대백과 전태일 https://encykorea.aks.ac.kr/Article/E0068917 ; 경향신문 https://www.khan.co.kr/article/201311072152055'),
('R-D3',ARRAY['D3'],'fun',800,'옥상 — 난간 안전 인솔 필요.','나무위키 세운상가 https://namu.wiki/w/세운상가 ; 국립민속박물관 웹진 https://webzine.nfm.go.kr/2015/11/23/한국-최초의-주상복합의-흥망성쇠/'),
('R-D4',ARRAY['D4'],'fun',800,'null','DH 교육용 위키 https://dh.aks.ac.kr/Edu/wiki/index.php/익선동_한옥마을_탄생과_역사.문화_가치 ; 서울& https://www.seouland.com/arti/culture/culture_general/4803.html'),
('R-D5',ARRAY['D5'],'neighbor',800,'null','위키백과 광장시장 https://ko.wikipedia.org/wiki/광장시장 ; 한국민족문화대백과 광장회사 https://encykorea.aks.ac.kr/Article/E0078008')
on conflict (reading_id) do update set served_place_ids=excluded.served_place_ids,theme=excluded.theme,word_target=excluded.word_target,operational_note=excluded.operational_note,source_ref=excluded.source_ref;

commit;
